# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-12 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_font'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-id']},
        ),
    ]
